updates for heating_control

diff --git a/init.d/heatingcontrol b/init.d/heatingcontrol
--- a/init.d/heatingcontrol
+++ b/init.d/heatingcontrol
@@ -1,19 +1,19 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:          myservice
+# Provides:          heatingcontrol
 # Required-Start:    $remote_fs $syslog
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Put a short description of the service here
-# Description:       Put a long description of the service here
+# Short-Description: Starts heating-control server
+# Description:       Starts heating-control server
 ### END INIT INFO
 
 # Change the next 3 lines to suit where you install your script and what you want to call it
-DIR=/home/pi/doorguard
-CHECKER=$DIR/checker.py
-CHECKER_NAME=doorguard_checker
+DIR=/home/pi/raspi-heating-control
+#CHECKER=$DIR/checker.py
+#CHECKER_NAME=doorguard_checker
 SERVER=$DIR/server.sh
 SERVER_NAME=doorguard_server
 
@@ -22,28 +22,28 @@ DAEMON_OPTS=""
 
 # This next line determines what user the script runs as.
 # Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
-CHECKER_USER=root
-SERVER_USER=pi
+#CHECKER_USER=root
+SERVER_USER=root
 
 # The process ID of the script when it runs is stored here:
-CHECKERPID=/var/run/$CHECKER_NAME.pid
+#CHECKERPID=/var/run/$CHECKER_NAME.pid
 SERVERPID=/var/run/$SERVER_NAME.pid
 
 . /lib/lsb/init-functions
 
 do_start () {
-    log_daemon_msg "Starting system $CHECKER_NAME daemon"
-    start-stop-daemon --start --background --pidfile $CHECKERPID --make-pidfile --user $CHECKER_USER --chuid $CHECKER_USER --startas $CHECKER -- $DAEMON_OPTS
-    log_end_msg $?
+    #log_daemon_msg "Starting system $CHECKER_NAME daemon"
+    #start-stop-daemon --start --background --pidfile $CHECKERPID --make-pidfile --user $CHECKER_USER --chuid $CHECKER_USER --startas $CHECKER -- $DAEMON_OPTS
+    #log_end_msg $?
     
     log_daemon_msg "Starting system $SERVER_NAME daemon"
     start-stop-daemon --start --background --pidfile $SERVERPID --make-pidfile --user $SERVER_USER --chuid $SERVER_USER --startas $SERVER -- $DAEMON_OPTS
     log_end_msg $?
 }
 do_stop () {
-    log_daemon_msg "Stopping system $CHECKER_NAME daemon"
-    start-stop-daemon --stop --pidfile $CHECKERPID --retry 10
-    log_end_msg $?
+    #log_daemon_msg "Stopping system $CHECKER_NAME daemon"
+    #start-stop-daemon --stop --pidfile $CHECKERPID --retry 10
+    #log_end_msg $?
     
     log_daemon_msg "Stopping system $SERVER_NAME daemon"
     start-stop-daemon --stop --pidfile $SERVERPID --retry 10
@@ -62,11 +62,12 @@ case "$1" in
         ;;
 
     status)
-        status_of_proc "$CHECKER_NAME" "$CHECKER" && status_of_proc "$SERVER_NAME" "$SERVER" && exit 0 || exit $?
+        #status_of_proc "$CHECKER_NAME" "$CHECKER" &&
+        status_of_proc "$SERVER_NAME" "$SERVER" && exit 0 || exit $?
         ;;
 
     *)
-        echo "Usage: /etc/init.d/doorguard {start|stop|restart|status}"
+        echo "Usage: /etc/init.d/heatingcontrol {start|stop|restart|status}"
         exit 1
         ;;
 
